https://www.mygov.in/corona-data/covid19-statewise-status/

https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally/

### Import Libraries

In [89]:
# importing the Libraries
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import time

### What we want to scrape

In [12]:
page = 1
sources = requests.get('https://science.thewire.in/covid19')
print(sources) 
#parsing the whole page
soup = BeautifulSoup(sources.content,"html.parser")
# looping over each card in a single page
for card in soup.findAll( 'div',{"id":"sec1"}):   
    print(card)

<Response [200]>
<div class="one-chart" id="sec1">
<div class="flourish-embed flourish-table" data-src="visualisation/2298241" data-url="https://flo.uri.sh/visualisation/2298241/embed"></div>
</div>

In [226]:
sources = requests.get('https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally/')
print(sources) 
#parsing the whole page
soup = BeautifulSoup(sources.content,"html.parser")
# looping over each card in a single page  
state_list, dist_list = [], []
for i in soup.findAll('div',{'class':'skgm-td state-td'}):
    state_list.append(i.text)
for i in soup.findAll('div',{'class':'skgm-tr'}):
    dist_list.append(i.text)
print(len(state_list))
print(len(dist_list))

<Response [200]>
36
810

In [230]:
def GetCovidTotal():
    sources = requests.get('https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally/')
    print(sources) 
    if sources.status_code!=200:
        return 'url data not available'
    #parsing the whole page
    soup = BeautifulSoup(sources.content,"html.parser")
    # looping over each card in a single page  
    for i in soup.findAll('div',{'class':'col col-sm contact-section'}):
        date = i.text
    state_list, dist_list = [], []
    for i in soup.findAll('div',{'class':'skgm-td state-td'}):
        state_list.append(i.text)
    for i in soup.findAll('div',{'class':'skgm-tr'}):
        dist_list.append(i.text)
    No_State = len(state_list)
    No_dist = (len(dist_list)-No_State)      # dist_list contain state name alse
    for card in soup.findAll( 'div',{"class":"skgm-th total-cases"}):   
        for i in card.findAll('div',{'class':'td-tc'}):
            Cases = i.text
        for i in card.findAll('div',{'class':'td-tdc'}):
             Last_Cases = i.text
        for i in card.findAll('div',{'class':'td-tr'}):
            Cured = i.text
        for i in card.findAll('div',{'class':'td-tdr'}):
            Last_Cured = (i.text)
        for i in card.findAll('div',{'class':'td-ta'}):
            Active = i.text
        for i in card.findAll('div',{'class':'td-td'}):
            Deaths = i.text
        for i in card.findAll('div',{'class':'td-tdd'}):
            Last_Deaths = i.text
    data = {'Date':date, 'Overall Total':{'Cases':Cases, 'Cured':Cured, 'Active':Active, 'Deaths':Deaths},
            'Last 24 hours Increase':{'Cases':Last_Cases, 'Cured':Last_Cured, 'Deaths':Last_Deaths},
            'In available data from ( https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally/ )':
            {'Number of States and Union Territories of INDIA ':No_State,
            'List of States and Union Territories of INDIA ':state_list,
            'Number of Districts and other state':No_dist}
            }
    return data
data1 = GetCovidTotal()

<Response [200]>

In [231]:
data1

{'Date': 'Monday, April 5, 2021',
 'Overall Total': {'Cases': '12675963',
  'Cured': '11728127',
  'Active': '777304',
  'Deaths': '165523'},
 'Last 24 hours Increase': {'Cases': '88042',
  'Cured': '48166',
  'Deaths': '391'},
 'In available data from ( https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally/ )': {'Number of States and Union Territories of INDIA ': 36,
  'List of States and Union Territories of INDIA ': [' Maharashtra',
   ' Kerala',
   ' Karnataka',
   ' Andhra Pradesh',
   ' Tamil Nadu',
   ' Delhi',
   ' Uttar Pradesh',
   ' West Bengal',
   ' Chhattisgarh',
   ' Odisha',
   ' Rajasthan',
   ' Gujarat',
   ' Telangana',
   ' Madhya Pradesh',
   ' Haryana',
   ' Bihar',
   ' Punjab',
   ' Assam',
   ' Jammu and Kashmir',
   ' Jharkhand',
   ' Uttarakhand',
   ' Himachal Pradesh',
   ' Goa',
   ' Puducherry',
   ' Tripura',
   ' Manipur',
   ' Chandigarh',
   ' Arunachal Pradesh',
   ' Meghalaya',
   ' Nagaland',
   ' Ladakh',
   ' Sikkim',
   ' Andaman and Nicobar Islands',
   ' Mizoram',
   ' Dadra and Nagar Haveli and Daman and Diu',
   ' Lakshadweep'],
  'Number of Districts and other state': 774}}

In [ ]:
# importing the Libraries
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd

In [211]:
sources = requests.get('https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally1/')
print(sources)

<Response [404]>

In [212]:
def GetCovidStateData():
    STATE_UT = []
    Cases = []
    Cured = []
    Active = []
    Deaths = []
    sources = requests.get('https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally/')
    print(sources) 
    if sources.status_code!=200:
        return 'url data not available'
    #parsing the whole page
    soup = BeautifulSoup(sources.content,"html.parser")
    # looping over each card in a single page
    for card in soup.findAll( 'section',{"id":"covid-19-table"}):   
        for i in card.findAll('div',{'class':'skgm-td state-td'}):
            STATE_UT.append(i.text)
        for i in card.findAll('div',{'class':'td-sc'}):
            Cases.append(i.text)
        for i in card.findAll('div',{'class':'td-sr'}):
            Cured.append(i.text)
        for i in card.findAll('div',{'class':'td-sa'}):
            Active.append(i.text)
        for i in card.findAll('div',{'class':'td-sd'}):
            Deaths.append(i.text)
    # creating the dataframe and assigning each column with the data from the lists 
    df = pd.DataFrame({
        'STATE_UT': STATE_UT,
        'Cases':Cases,
        'Cured':Cured,
        'Active':Active,
        'Deaths':Deaths
        })
    return df
df1 = GetCovidStateData()

<Response [200]>

In [213]:
def GetCovidDistrictData():
    temp_dist = []
    Districts = []
    Cases = []
    Cured = []
    Active = []
    Deaths = []
    sources = requests.get('https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally/')
    print(sources)
    if sources.status_code!=200:
        return 'url data not available'
    #parsing the whole page
    soup = BeautifulSoup(sources.content,"html.parser")
    # looping over each card in a single page
    for card in soup.findAll( 'div',{"class":"skgm-districts"}):   
        for i in card.findAll('div',{'class':'skgm-tr'}):
            for i in i.findAll('div',{'class':'skgm-td'}):
                temp_dist.append(i.text)
        for i in card.findAll('div',{'class':'td-dc'}):
            Cases.append(i.text)
        for i in card.findAll('div',{'class':'td-dr'}):
            Cured.append(i.text)
        for i in card.findAll('div',{'class':'td-da'}):
            Active.append(i.text)
        for i in card.findAll('div',{'class':'td-dd'}):
            Deaths.append(i.text)
    # Find out only District
    for i in range(0,len(temp_dist),5):
        Districts.append(temp_dist[i])
    # creating the dataframe and assigning each column with the data from the lists 
    df_temp = pd.DataFrame({
        'Districts': Districts,
        'Cases':Cases,
        'Cured':Cured,
        'Active':Active,
        'Deaths':Deaths
        })
    df1 = GetCovidStateData()    # Get covid state wise data
    if type(df1)==str:
        return'Covid State Data data not available'
    state = list(df1['STATE_UT'])
    num_dist = []
    for card in soup.findAll( 'div',{"class":"skgm-states"}): 
        w = 0
        for i in card.findAll('div',{'class':"skgm-tr"}):
            w+=1
            #print(i.text)
        #print(w-1)       # w-1 because it contain state name also
        num_dist.append(w-1)
    state_list = []
    for index,numb in enumerate(num_dist):
        for j in range(0,numb):
            state_list.append(state[index])
    # final df 
    df = df_temp
    df['STATE_UT'] = state_list
    return df

df2 = GetCovidDistrictData()

<Response [200]>
<Response [200]>

In [214]:
df1.head()

          STATE_UT    Cases    Cured  Active Deaths
0      Maharashtra  3057885  2549075  451375  56033
1           Kerala  1137591  1104225   28370   4681
2        Karnataka  1020434   965275   42483  12657
3   Andhra Pradesh   909002   891048   10710   7244
4       Tamil Nadu   903479   866913   23777  12789

In [233]:
df2.head()

  Districts   Cases   Cured Active Deaths      STATE_UT
0      Pune  584969  495102  81378   8440   Maharashtra
1    Mumbai  462560  376484  73281  11800   Maharashtra
2     Thane  367440  303638  57635   6136   Maharashtra
3    Nagpur  249867  189814  55926   4081   Maharashtra
4    Nashik  197725  160869  34540   2315   Maharashtra

In [234]:
df2[df2['STATE_UT']=='Maharashtra']

Empty DataFrame
Columns: [Districts, Cases, Cured, Active, Deaths, STATE_UT]
Index: []

In [191]:
df2.head()

  Districts   Cases   Cured Active Deaths
0      Pune  576758  486958  81317   8434
1    Mumbai  452681  373113  66803  11779
2     Thane  361654  302267  53230   6126
3    Nagpur  246239  188484  53638   4071
4    Nashik  193555  159515  31737   2302

In [198]:

# sources = requests.get('https://www.grainmart.in/news/covid-19-coronavirus-india-state-and-district-wise-tally/')
# print(sources) 
#parsing the whole page
# soup = BeautifulSoup(sources.content,"html.parser")
# looping over each card in a single page
num_dist = []
for card in soup.findAll( 'div',{"class":"skgm-states"}): 
    w = 0
    for i in card.findAll('div',{'class':"skgm-tr"}):
        w+=1
#         print(i.text)
#     print(w-1)
    num_dist.append(w-1)
print(len(num_dist))
print(sum(num_dist))
print(num_dist)

36
774
[37, 15, 31, 15, 40, 12, 75, 24, 29, 32, 37, 34, 36, 53, 24, 38, 22, 36, 22, 25, 13, 12, 4, 4, 8, 18, 2, 25, 11, 12, 2, 5, 4, 11, 4, 2]

In [206]:
state_list = []
for index,numb in enumerate(num_dist):
    for j in range(0,numb):
        state_list.append(state[index])
len(state_list)

774

In [207]:
df3 = df2
df3['STATE_UT'] = state_list
df3.head()

  Districts   Cases   Cured Active Deaths      STATE_UT
0      Pune  576758  486958  81317   8434   Maharashtra
1    Mumbai  452681  373113  66803  11779   Maharashtra
2     Thane  361654  302267  53230   6126   Maharashtra
3    Nagpur  246239  188484  53638   4071   Maharashtra
4    Nashik  193555  159515  31737   2302   Maharashtra

In [209]:
df3.tail(7)

,Districts,Cases,Cured,Active,Deaths,STATE_UT
767,Khawzawl,23,23,0,0,Mizoram
768,Dadra and Nagar Haveli,1859,1714,139,1,Dadra and Nagar Haveli and Daman and Diu
769,Daman,1550,1464,60,1,Dadra and Nagar Haveli and Daman and Diu
770,Diu,312,312,0,0,Dadra and Nagar Haveli and Daman and Diu
771,Other State,0,0,0,0,Dadra and Nagar Haveli and Daman and Diu
772,Lakshadweep,727,674,47,1,Lakshadweep
773,Unknown,14,25,-11,0,Lakshadweep

In [52]:
sources = requests.get('https://www.mygov.in/corona-data/covid19-statewise-status/')
print(sources) 
#parsing the whole page
soup = BeautifulSoup(sources.content,"html.parser")
# looping over each card in a single page
for card in soup.findAll( 'div',{'class':'field field-name-field-covid-india-as-on field-type-text field-label-above'}):   
    print(card.text)

<Response [200]>
Covid India As On: 05 Apr 2021, 08:00 IST (GMT+5:30)

In [73]:
sources = requests.get('https://www.mygov.in/corona-data/covid19-statewise-status/')
print(sources) 
#parsing the whole page
soup = BeautifulSoup(sources.content,"html.parser")
for i in soup.findAll('div',{'class':'field field-name-field-total-vaccinations field-type-text field-label-above'}):
    for j in i.findAll('div',{'class':'field-items'}):
        Total_Vaccinations = j.text
#     print(Total_Vaccinations)
for i in soup.findAll('div',{'class':'field field-name-field-total-vaccinations-today field-type-text field-label-above'}):
    for j in i.findAll('div',{'class':'field-items'}):
        Total_Vaccinations_Today = j.text
#     print(Total_Vaccinations_Today)
for i in soup.findAll('div',{'class':'field field-name-field-last-vaccination-date field-type-text field-label-above'}):
    for j in i.findAll('div',{'class':'field-items'}):
        Last_Vaccination_date = j.text
#     print(Last_Vaccination_date)
    
# looping over each card in a single page
for card in soup.findAll( 'div',{'class':'content'}):   
    for i in card.findAll('div',{'class':'field field-name-field-covid-india-as-on field-type-text field-label-above'}):
        for j in i.findAll('div',{'class':'field-items'}):
            date_time = j.text
#         print(date_time)
    for i in card.findAll('div',{'class':'field field-name-field-district-reporting field-type-text field-label-above'}):
        for j in i.findAll('div',{'class':'field-items'}):
            District_Reporting = j.text
#         print(District_Reporting)
    for i in card.findAll('div',{'class':'field field-name-field-last-total-active field-type-number-integer field-label-above'}):
        for j in i.findAll('div',{'class':'field-items'}):
            Last_Total_Active_Case = j.text
#         print(Last_Total_Active_Case)
    for i in card.findAll('div',{'class':'field field-name-field-last-total-cured field-type-number-integer field-label-above'}):
        for j in i.findAll('div',{'class':'field-items'}):
            Last_Total_Cured = j.text
#         print(Last_Total_Cured)
    for i in card.findAll('div',{'class':'field field-name-field-last-total-death field-type-number-integer field-label-above'}):
        for j in i.findAll('div',{'class':'field-items'}):
            Last_Total_death = j.text
#         print(Last_Total_death)
data = {'Date Time':date_time
        ,'District Reporting PDF url':District_Reporting
        , 'Last Total Active Case':Last_Total_Active_Case
        , 'Last Total Cured':Last_Total_Cured
        , 'Last Total death':Last_Total_death
        , 'Total Vaccinations':Total_Vaccinations
        , 'Total Vaccinations Today':Total_Vaccinations_Today
        , 'Last Vaccination date':Last_Vaccination_date
       }

<Response [200]>

In [86]:
# importing the Libraries
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd

def GetOverAllInfo():
    sources = requests.get('https://www.mygov.in/corona-data/covid19-statewise-status/')
    print(sources) 
    soup = BeautifulSoup(sources.content,"html.parser")
    for i in soup.findAll('div',{'class':'field field-name-field-total-vaccinations field-type-text field-label-above'}):
        for j in i.findAll('div',{'class':'field-items'}):
            Total_Vaccinations = j.text
    for i in soup.findAll('div',{'class':'field field-name-field-total-vaccinations-today field-type-text field-label-above'}):
        for j in i.findAll('div',{'class':'field-items'}):
            Total_Vaccinations_Today = j.text
    for i in soup.findAll('div',{'class':'field field-name-field-last-vaccination-date field-type-text field-label-above'}):
        for j in i.findAll('div',{'class':'field-items'}):
            Last_Vaccination_date = j.text

    # looping over each card in a single page
    for card in soup.findAll( 'div',{'class':'content'}):   
        for i in card.findAll('div',{'class':'field field-name-field-covid-india-as-on field-type-text field-label-above'}):
            for j in i.findAll('div',{'class':'field-items'}):
                date_time = j.text
        for i in card.findAll('div',{'class':'field field-name-field-district-reporting field-type-text field-label-above'}):
            for j in i.findAll('div',{'class':'field-items'}):
                District_Reporting = j.text
        for i in card.findAll('div',{'class':'field field-name-field-last-total-active field-type-number-integer field-label-above'}):
            for j in i.findAll('div',{'class':'field-items'}):
                Last_Total_Active_Case = j.text
        for i in card.findAll('div',{'class':'field field-name-field-last-total-cured field-type-number-integer field-label-above'}):
            for j in i.findAll('div',{'class':'field-items'}):
                Last_Total_Cured = j.text
        for i in card.findAll('div',{'class':'field field-name-field-last-total-death field-type-number-integer field-label-above'}):
            for j in i.findAll('div',{'class':'field-items'}):
                Last_Total_death = j.text
    if sources.status_code==200:
#         print(sources.status_code)
        data = {'Date Time':date_time
                ,'District Reporting PDF url':District_Reporting
                , 'Last Total Active Case':Last_Total_Active_Case
                , 'Last Total Cured':Last_Total_Cured
                , 'Last Total death':Last_Total_death
                , 'Total Vaccinations':Total_Vaccinations
                , 'Total Vaccinations Today':Total_Vaccinations_Today
                , 'Last Vaccination date':Last_Vaccination_date
               }
    else:
#         print(sources.status_code)
        data = {'Data':'data not available'}
    return data

GetOverAllInfo()

<Response [200]>

{'Date Time': '05 Apr 2021, 08:00 IST (GMT+5:30)',
 'District Reporting PDF url': 'https://www.mohfw.gov.in/pdf/StatewiseCovidHospitalslink19062020.pdf',
 'Last Total Active Case': '6,91,597',
 'Last Total Cured': '1,16,29,289',
 'Last Total death': '1,64,623',
 'Total Vaccinations': '79105163',
 'Total Vaccinations Today': '1638464',
 'Last Vaccination date': 'April 04, 2021'}

In [88]:
def GetSataWiseData():
    STATE_NAME = []
    TOTAL_CONFIRMED = []
    CURED_DISCHARGED_MIGRATED = []
    DEATH = []
    sources = requests.get('https://www.mygov.in/corona-data/covid19-statewise-status/')
    #parsing the whole page
    soup = BeautifulSoup(sources.content,"html.parser")
    for card in soup.findAll( 'div',{'class':"field field-name-field-select-state field-type-list-text field-label-above"}):   
        for i in card.findAll('div',{'class':'field-items'}):
            STATE_NAME.append(i.text)
    for card in soup.findAll( 'div',{'class':"field field-name-field-total-confirmed-indians field-type-number-integer field-label-above"}):   
        for i in card.findAll('div',{'class':'field-items'}):
            TOTAL_CONFIRMED.append(i.text)
    for card in soup.findAll( 'div',{'class':"field field-name-field-cured field-type-number-integer field-label-above"}):   
        for i in card.findAll('div',{'class':'field-items'}):
            CURED_DISCHARGED_MIGRATED.append(i.text)
    for card in soup.findAll( 'div',{'class':"field field-name-field-deaths field-type-number-integer field-label-above"}):   
        for i in card.findAll('div',{'class':'field-items'}):
            DEATH.append(i.text)
    # creating the dataframe and assigning each column with the data from the lists 
    df = pd.DataFrame({
        'STATE_NAME': STATE_NAME,
        'TOTAL_CONFIRMED':TOTAL_CONFIRMED,
        'CURED_DISCHARGED_MIGRATED':CURED_DISCHARGED_MIGRATED,
        'DEATH':DEATH
        })
    return df
GetSataWiseData()

,STATE_NAME,TOTAL_CONFIRMED,CURED_DISCHARGED_MIGRATED,DEATH
0,Andaman and Nicobar,5109,4990,62
1,Andhra Pradesh,907676,890137,7239
2,Arunachal Pradesh,16849,16785,56
3,Assam,218670,215597,1109
4,Bihar,268377,263233,1583
5,Chandigarh,28194,24661,383
6,Chhattisgarh,369046,326277,4319
7,Dadra and Nagar Haveli and Daman and Diu,3744,3538,2
8,Delhi,676414,651351,11081
9,Goa,59068,56156,835
10,Gujarat,318438,298737,4566
11,Haryana,298133,282368,3191
12,Himachal Pradesh,65242,60595,1070
13,Jammu and Kashmir,133012,127049,2008
14,Jharkhand,127246,120872,1130
15,Karnataka,1015155,963419,12625
16,Kerala,1135233,1102359,4668
17,Ladakh,10255,9802,130
18,Lakshadweep,741,704,1
19,Maharashtra,3010597,2522823,55878
20,Manipur,29423,28988,374
21,Meghalaya,14122,13870,150
22,Mizoram,4491,4439,11
23,Madhya Pradesh,306851,281476,4040
24,Nagaland,12363,12138,92
25,Odisha,342695,337935,1922
26,Puducherry,42359,40083,684
27,Punjab,251460,219063,7083
28,Rajasthan,339325,323618,2829
29,Sikkim,6257,6071,135
30,Tamil Nadu,899807,865071,12778
31,Telengana,313237,302768,1723
32,Tripura,33540,33085,392
33,Uttar Pradesh,630059,601440,8881
34,Uttarakhand,102264,97520,1727
35,West Bengal,593615,573118,10344

In [60]:
STATE_NAME = []
TOTAL_CONFIRMED = []
CURED_DISCHARGED_MIGRATED = []
DEATH = []

sources = requests.get('https://www.mygov.in/corona-data/covid19-statewise-status/')
#parsing the whole page
soup = BeautifulSoup(sources.content,"html.parser")

for card in soup.findAll( 'div',{'class':"field field-name-field-select-state field-type-list-text field-label-above"}):   
    for i in card.findAll('div',{'class':'field-items'}):
        STATE_NAME.append(i.text)
for card in soup.findAll( 'div',{'class':"field field-name-field-total-confirmed-indians field-type-number-integer field-label-above"}):   
    for i in card.findAll('div',{'class':'field-items'}):
        TOTAL_CONFIRMED.append(i.text)
for card in soup.findAll( 'div',{'class':"field field-name-field-cured field-type-number-integer field-label-above"}):   
    for i in card.findAll('div',{'class':'field-items'}):
        CURED_DISCHARGED_MIGRATED.append(i.text)
for card in soup.findAll( 'div',{'class':"field field-name-field-deaths field-type-number-integer field-label-above"}):   
    for i in card.findAll('div',{'class':'field-items'}):
        DEATH.append(i.text)
# creating the dataframe and assigning each column with the data from the lists 

df = pd.DataFrame({
    'STATE_NAME': STATE_NAME,
    'TOTAL_CONFIRMED':TOTAL_CONFIRMED,
    'CURED_DISCHARGED_MIGRATED':CURED_DISCHARGED_MIGRATED,
    'DEATH':DEATH
    })
df.head()

,STATE_NAME,TOTAL_CONFIRMED,CURED_DISCHARGED_MIGRATED,DEATH
0,Andaman and Nicobar,5109,4990,62
1,Andhra Pradesh,907676,890137,7239
2,Arunachal Pradesh,16849,16785,56
3,Assam,218670,215597,1109
4,Bihar,268377,263233,1583
5,Chandigarh,28194,24661,383
6,Chhattisgarh,369046,326277,4319
7,Dadra and Nagar Haveli and Daman and Diu,3744,3538,2
8,Delhi,676414,651351,11081
9,Goa,59068,56156,835
10,Gujarat,318438,298737,4566
11,Haryana,298133,282368,3191
12,Himachal Pradesh,65242,60595,1070
13,Jammu and Kashmir,133012,127049,2008
14,Jharkhand,127246,120872,1130
15,Karnataka,1015155,963419,12625
16,Kerala,1135233,1102359,4668
17,Ladakh,10255,9802,130
18,Lakshadweep,741,704,1
19,Maharashtra,3010597,2522823,55878
20,Manipur,29423,28988,374
21,Meghalaya,14122,13870,150
22,Mizoram,4491,4439,11
23,Madhya Pradesh,306851,281476,4040
24,Nagaland,12363,12138,92
25,Odisha,342695,337935,1922
26,Puducherry,42359,40083,684
27,Punjab,251460,219063,7083
28,Rajasthan,339325,323618,2829
29,Sikkim,6257,6071,135
30,Tamil Nadu,899807,865071,12778
31,Telengana,313237,302768,1723
32,Tripura,33540,33085,392
33,Uttar Pradesh,630059,601440,8881
34,Uttarakhand,102264,97520,1727
35,West Bengal,593615,573118,10344

In [49]:
column_names = {"rows":{"columns":["State","Cases*","Active*","Cured/Discharged*","Deaths*","Active","Cured/Discharged","Deaths","January 1","January 2","January 3","January 4","January 5","January 6","January 7","January 8","January 9","January 10","January 11","January 12","January 13","January 14","January 15","January 16","January 17","January 18","January 19","January 20","January 21","January 22","January 23","January 24","January 25","January 26","January 27","January 28","January 29","January 30","January 31","February 1","February 2","February 3","February 4","February 5","February 6","February 7","February 8","February 9","February 10","February 11","February 12","February 13","February 14","February 15","February 16","February 17","February 18","February 19","February 20","February 21","February 22","February 23","February 24","February 25","February 26","February 27","February 28","March 1","March 2","March 3","March 4","March 5","March 6","March 7","March 8","March 9","March 10","March 11","March 12","March 13","March 14","March 15","March 16","March 17","March 18","March 19","March 20","March 21","March 22","March 23","March 24","March 25","March 26","March 27","March 28","March 29","March 30","March 31","April 1","April 2","April 3","April 4","April 5"]}},
# data_metadata = {"rows":{"columns":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]}}
data = {"rows":[{"columns":["## India","**12589067** (↑103558)","**741830** (↑50233)","**11682136** (↑52847)","**165101** (↑478)","741830","11682136","165101","254254","250183","247220","243953","231036","227546","228083","225449","224190","223335","222526","216558","214507","213603","213027","211033","208826","208012","200528","197201","192308","188688","185662","184408","184182","177266","176498","173740","171686","169824","168784","168235","163353","160057","155025","151460","148590","148766","148609","143625","141511","142562","135926","136571","137567","139637","136872","136549","137342","139542","143127","145634","150055","147306","146907","151708","155986","159590","164511","168627","168358","170126","173413","176319","180304","184523","188747","187462","184598","189226","197237","202022","210544","219262","223432","234406","252364","271282","288394","309087","334646","345377","368457","395192","421066","452647","486310","521808","540720","552566","584055","614696","658909","691597","741830"]},{"columns":["Maharashtra","**3010597** (↑57074)","**431896** (↑29344)","**2522823** (↑27508)","**55878** (↑222)","431896","2522823","55878","54045","53231","54288","55471","49955","50223","51969","52276","53006","54129","55351","53463","53067","53544","53744","53344","53163","53852","51887","49615","47982","46836","46146","45093","46057","44789","45041","44624","44282","44384","45437","46312","44944","42830","38762","36113","35188","36192","37213","35991","35917","36917","31437","32649","34449","37146","37383","38307","39201","42047","45956","49630","54149","54306","54604","60559","65461","68810","73734","78212","78825","80302","83556","86359","90055","94115","99205","98859","96548","100240","107307","111724","119771","127480","131812","140079","154036","167637","178848","192294","211416","216540","231942","248604","264001","283772","304809","327241","337928","341887","357604","367897","391203","402552","431896"]},{"columns":["Kerala","**1135233** (↑2802)","**28206** (↑619)","**1102359** (↑2173)","**4668** (↑10)","28206","1102359","4668","65381","65238","65560","65467","63324","63993","65252","64639","64434","64516","64379","63547","64759","65579","66713","67711","68633","69209","68617","70481","69914","69998","70624","72278","73121","70859","71843","72476","72634","72482","71714","71229","69456","69409","69365","69109","68047","67795","67903","65670","64390","64607","64180","64227","63847","63752","61550","61030","61074","60451","60087","58883","58593","55752","54949","53153","52164","51679","50803","49709","48159","47569","46288","44734","43856","43114","41162","39532","37446","35715","34082","32471","31238","29777","27357","26428","25698","25463","25465","25317","24928","24389","24192","24578","24690","24584","24541","24892","24533","24960","25559","26511","26718","27587","28206"]},{"columns":["Karnataka","**1015155** (↑4553)","**39111** (↑2478)","**963419** (↑2060)","**12625** (↑15)","39111","963419","12625","11290","11077","10853","10912","10226","9656","9196","9138","9448","9471","9668","9363","8928","8906","8747","8809","8713","8599","8052","7884","7716","7573","7004","7361","7529","6865","6652","6317","6221","6080","5995","6048","5963","5943","5934","5936","5893","5987","5978","5953","5804","5894","5977","5944","5929","5855","5791","5879","5717","5811","5901","5997","6055","6080","6081","6096","5595","5520","5657","5823","5843","5964","6076","6147","6393","6613","6881","6834","7052","7475","7820","8133","8061","8383","8879","9447","10239","11378","12086","12847","13512","14286","15614","16905","18226","19572","21271","23056","23868","25560","28267","30884","34238","36633","39111"]},{"columns":["Andhra Pradesh","**907676** (↑1730)","**10300** (↑883)","**890137** (↑842)","**7239** (↑5)","10300","890137","7239","3262","3238","3194","3070","2943","3038","2896","2822","2832","2607","2544","2450","2411","2382","2338","2199","1987","1896","1713","1660","1637","1522","1488","1473","1476","1389","1357","1369","1358","1308","1289","1278","1242","1197","1162","1154","1071","1012","1003","962","917","845","853","814","797","735","695","615","607","619","620","604","620","590","575","603","611","635","667","718","725","774","826","871","900","921","998","1009","1038","1064","1158","1227","1268","1400","1443","1579","1694","1795","1909","2083","2188","2382","2616","2946","3469","4145","4715","5394","6104","6614","7338","8142","8815","9417","10300"]},{"columns":["Tamil Nadu","**899807** (↑3581)","**21958** (↑1754)","**865071** (↑1813)","**12778** (↑14)","21958","865071","12778","8501","8380","8272","8127","7970","7808","7665","7547","7432","7304","7164","6971","6807","6653","6488","6299","6128","5940","5725","5487","5314","5196","5073","4984","4904","4813","4736","4676","4629","4601","4575","4554","4532","4517","4494","4467","4446","4417","4389","4354","4328","4309","4294","4285","4275","4260","4232","4206","4192","4173","4147","4120","4109","4091","4074","4062","4053","4046","4036","4022","4009","3997","3990","3978","3954","3952","3997","4018","4073","4207","4344","4483","4662","4870","5149","5450","5811","6222","6690","7291","7903","8619","9145","9746","10487","11318","12157","13070","13983","14846","15879","17043","18606","20204","21958"]},{"columns":["Delhi","**676414** (↑4033)","**13982** (↑1335)","**651351** (↑2677)","**11081** (↑21)","13982","651351","11081","5511","5358","5342","5044","4689","4562","4481","4168","3779","3683","3468","3354","3179","2991","2937","2795","2691","2544","2335","2334","2147","2120","2060","1880","1741","1694","1626","1501","1575","1551","1436","1361","1265","1217","1208","1194","1206","1174","1112","1096","1052","1177","1051","1053","1041","1031","1036","1019","1078","1053","1053","1025","1071","1041","1009","1137","1169","1231","1307","1335","1404","1543","1584","1701","1779","1779","1803","1730","1812","1900","2020","2093","2207","2262","2321","2488","2702","2927","3165","3409","3618","3934","4411","4890","5497","6051","6625","7545","8029","7429","8838","10498","11994","12647","13982"]},{"columns":["Uttar Pradesh","**630059** (↑4136)","**19738** (↑3242)","**601440** (↑863)","**8881** (↑31)","19738","601440","8881","14260","13831","13316","12858","12505","12286","11939","11787","11535","11221","11134","10864","10560","10132","10080","9581","9162","8881","8631","8172","7873","7717","7528","7330","7082","6813","6537","6368","6230","5918","5682","5525","5303","5007","4765","4629","4462","4438","3880","3442","3306","3256","3320","3232","3098","3040","2974","2853","2690","2587","2521","2432","2370","2366","2268","2190","2182","2184","2146","2103","2078","2082","2025","2029","2017","1731","1647","1634","1678","1689","1742","1819","1817","1851","1838","1912","2014","2217","2470","2774","3036","3396","3844","4388","5049","5824","6667","7692","8669","9195","9848","11918","14073","16496","19738"]},{"columns":["West Bengal","**593615** (↑1957)","**10153** (↑1309)","**573118** (↑644)","**10344** (↑4)","10153","573118","10344","11985","11616","11008","10446","9671","9293","8868","8476","8245","8034","7881","7538","7392","7303","7272","7223","7151","7083","6893","6781","6675","6565","6470","6396","6323","6151","6028","5868","5781","5711","5671","5553","5420","5305","5196","5097","4992","4895","4794","4632","4496","4387","4313","4233","4160","4086","3960","3854","3736","3672","3625","3579","3525","3440","3399","3377","3353","3343","3333","3307","3293","3253","3245","3236","3226","3213","3163","3155","3144","3127","3110","3133","3139","3143","3147","3158","3188","3241","3297","3380","3504","3574","3656","3782","3950","4231","4608","4976","5152","5303","5775","6513","7692","8844","10153"]},{"columns":["Chhattisgarh","**369046** (↑5250)","**38450** (↑2138)","**326277** (↑3076)","**4319** (↑36)","38450","326277","4319","11435","11344","10517","9980","9766","9111","9109","8859","9045","9274","8967","8550","8060","7791","7418","6923","6867","6832","5995","5932","5798","5638","5308","5040","4943","4896","5021","4513","4450","4358","4260","4327","4124","4173","4315","4295","4360","4320","4290","4190","4172","4073","3475","3287","3255","3258","3039","2905","3009","3005","3039","3102","3112","2998","2977","2911","2865","2827","2767","2774","2880","2836","2961","2990","2816","2721","2820","2919","3023","3345","3537","3577","3770","4006","4098","4661","5299","6025","6753","7693","8442","9205","10491","11934","13318","15307","17836","19239","20181","22057","25529","28987","31858","36312","38450"]},{"columns":["Odisha","**342695** (↑471)","**2838** (↑170)","**337935** (↑300)","**1922** (↑1)","2838","337935","1922","2316","2257","2272","2217","2100","2025","2026","1973","1972","1908","1928","1943","1985","2024","2035","1963","1910","1864","1742","1613","1500","1418","1360","1284","1251","1240","1196","1226","1207","1120","1090","1063","1006","928","877","851","825","797","763","751","748","759","794","781","740","710","714","710","697","659","619","611","615","625","610","588","609","640","670","704","714","731","764","774","801","767","747","718","693","690","667","640","634","614","610","609","630","648","687","735","774","838","891","990","1132","1293","1413","1583","1672","1769","1905","2178","2421","2668","2838"]},{"columns":["Rajasthan","**339325** (↑1729)","**12878** (↑1140)","**323618** (↑587)","**2829** (↑2)","12878","323618","2829","9560","9223","8795","8491","8189","7830","7698","7468","7402","6730","6726","6585","6200","5780","5675","5608","5286","5050","4634","4304","4077","3934","3719","3448","3147","2968","2836","2664","2559","2395","2260","2161","1948","1798","1692","1638","1581","1527","1464","1470","1435","1450","1385","1407","1409","1409","1365","1257","1249","1275","1269","1300","1245","1206","1195","1204","1208","1231","1254","1308","1304","1340","1470","1509","1584","1703","1755","1883","1963","2032","2142","2242","2329","2453","2572","2661","2851","3023","3121","3310","3585","4006","4262","4672","5149","5733","6358","7159","7794","8155","8663","9563","10484","11738","12878"]},{"columns":["Gujarat","**318438** (↑2875)","**15135** (↑837)","**298737** (↑2024)","**4566** (↑14)","15135","298737","4566","9839","9663","9477","9250","9047","8830","8594","8359","8149","7968","7829","7695","7439","7226","7056","6850","6588","6400","6193","5967","5748","5491","5240","4960","4665","4345","4086","3976","3718","3589","3469","3450","3341","3203","2956","2800","2641","2491","2379","2160","2040","1800","1781","1767","1763","1739","1708","1699","1703","1696","1684","1672","1690","1732","1786","1869","1991","2136","2258","2363","2431","2522","2638","2749","2858","3025","3140","3212","3338","3529","3788","4006","4200","4422","4717","4966","5310","5684","6147","6737","7321","7847","8318","8823","9372","10134","10871","11528","12041","12263","12610","12996","13559","14298","15135"]},{"columns":["Telangana","**313237** (↑1097)","**8746** (↑823)","**302768** (↑268)","**1723** (↑6)","8746","302768","1723","5815","5571","5388","5106","5039","4982","5053","5000","4822","4756","4518","4524","4458","4495","4442","4273","4191","4049","4005","3919","3920","3781","3569","3389","3234","3072","2819","2698","2537","2354","2240","2092","2022","2008","1985","1964","1977","1939","1842","1804","1797","1825","1815","1781","1748","1676","1643","1640","1700","1715","1715","1731","1701","1697","1745","1852","1910","1939","1951","1902","1907","1912","1948","1963","1936","1886","1807","1769","1780","1855","1872","1918","1993","1983","2015","2101","2265","2434","2607","2804","2958","3151","3352","3684","3995","4241","4495","4583","4678","4965","5511","6159","6900","7923","8746"]},{"columns":["Madhya Pradesh","**306851** (↑3178)","**21335** (↑966)","**281476** (↑2201)","**4040** (↑11)","21335","281476","4040","9354","9222","9089","8852","8609","8427","8516","8528","8324","8029","7823","7651","7499","7294","7108","6957","6524","6399","6160","5732","5008","4599","4479","4310","4171","3508","3219","3053","2955","2826","2760","2665","2554","2423","2430","2331","2193","2074","2041","2041","1987","1951","1920","1862","1829","1842","1847","1856","1863","1909","1954","1994","2051","2104","2151","2270","2435","2518","2666","2785","2901","2973","3097","3308","3457","3527","3606","3638","3711","3915","4094","4335","4512","4740","5024","5286","5616","6032","6609","7344","8000","8592","9292","10047","11004","12038","12995","14185","15150","16034","17096","18057","19336","20369","21335"]},{"columns":["Haryana","**298133** (↑1904)","**12574** (↑787)","**282368** (↑1110)","**3191** (↑7)","12574","282368","3191","3567","3314","3124","2890","2737","2692","2672","2563","2501","2563","2510","2547","2441","2414","2266","2184","2129","2094","1929","1837","1734","1679","1585","1559","1511","1378","1284","1254","1240","1192","1134","1115","1081","1055","1019","962","949","908","883","870","854","824","848","837","845","852","903","819","826","814","813","816","861","874","908","955","1054","1103","1205","1275","1288","1348","1470","1615","1723","1898","2031","2083","2263","2440","2679","2807","2952","3095","3212","3484","3740","3957","4380","4830","5355","5698","6149","6745","7229","7795","8410","9120","9312","9437","9726","10362","11022","11787","12574"]},{"columns":["Bihar","**268377** (↑864)","**3561** (↑618)","**263233** (↑245)","**1583** (↑1)","3561","263233","1583","4870","4945","4792","4473","4380","4351","4184","4261","4075","4247","4178","4054","4234","4115","4170","4112","4046","3822","3308","3241","3143","2923","2682","2599","2317","2359","2336","1645","1043","1021","976","893","851","802","732","724","608","609","533","382","500","757","700","691","653","625","588","565","520","513","504","502","537","561","548","509","478","431","404","399","370","369","349","348","341","334","313","290","298","303","324","324","332","338","328","347","364","406","437","473","523","561","624","727","925","1001","1116","1347","1488","1456","1580","1908","2364","2943","3561"]},{"columns":["Punjab","**251460** (↑3006)","**25314**","**219063** (↑2955)","**7083** (↑51)","25314","219063","7083","3685","3517","3429","3361","3069","2983","2998","2975","3007","2952","2933","2858","2788","2817","2767","2739","2578","2617","2458","2412","2405","2343","2324","2293","2256","2152","2106","2080","2079","2114","2184","2128","2101","2122","2130","2159","2144","2156","2176","2112","2077","2112","2224","2300","2335","2360","2357","2401","2546","2642","2803","2883","3019","3167","3295","3598","3870","4222","4436","4632","4853","5198","5593","6264","6661","7164","7497","8020","8522","9402","10069","10452","10916","11550","11942","12616","13320","14366","15459","16988","18257","18628","19403","20522","21405","22652","23271","23917","24143","23731","23832","24644","25458","25314","25314"]},{"columns":["Assam","**218670** (↑69)","**1964** (↑19)","**215597** (↑48)","**1109** (↑2)","1964","215597","1109","3256","3210","3166","3120","3087","3075","3039","3046","3042","3019","3014","2992","2994","3003","2991","2963","2930","2919","2811","2728","2663","2568","2482","2407","2323","2265","2183","2104","2038","1956","1914","1881","1823","1793","1748","1728","1706","1695","1679","1671","1680","1674","1661","1657","1631","1621","1614","1605","1612","1614","1618","1616","1607","1603","1604","1606","1623","1634","1620","1615","1631","1632","1621","1626","1635","1625","1627","1624","1629","1633","1625","1628","1619","1619","1612","1613","1627","1645","1641","1650","1663","1670","1694","1719","1736","1747","1770","1800","1816","1846","1862","1884","1909","1945","1964"]},{"columns":["Jammu and Kashmir","**133012** (↑573)","**3955** (↑381)","**127049** (↑189)","**2008** (↑3)","3955","127049","2008","3009","3016","2999","2975","2684","2600","2459","2396","2241","2094","2011","1768","1682","1629","1468","1428","1280","1224","1111","1103","1099","1111","1098","1103","1103","1084","1103","1050","963","823","761","748","709","668","669","652","654","631","630","593","593","605","628","634","616","622","617","629","657","688","702","700","721","735","766","771","820","803","828","823","829","820","875","883","891","882","892","871","859","899","896","887","881","920","937","973","1008","1073","1152","1191","1290","1336","1410","1513","1593","1681","1813","2001","2110","2293","2531","2874","3215","3574","3955"]},{"columns":["Jharkhand","**127246** (↑788)","**5244** (↑631)","**120872** (↑149)","**1130** (↑8)","5244","120872","1130","1659","1682","1624","1601","1528","1422","1449","1448","1465","1494","1468","1382","1356","1356","1327","1289","1249","1225","1190","1147","1102","1032","978","878","821","772","772","723","670","628","576","553","513","489","453","447","441","428","431","438","464","464","456","441","452","461","464","460","466","467","467","459","453","448","447","431","467","492","492","494","485","498","473","486","481","461","463","472","494","520","511","509","515","548","556","577","599","624","653","722","756","796","854","969","1175","1399","1636","1871","1968","2254","2825","3352","3908","4613","5244"]},{"columns":["Uttarakhand","**102264** (↑550)","**3017** (↑379)","**97520** (↑169)","**1727** (↑2)","3017","97520","1727","4719","4577","4364","4376","3966","3717","3515","3309","3179","3215","3130","2753","2643","2552","2510","2406","2349","2354","2136","1992","2005","1876","1795","1733","1725","1523","1455","1439","1338","1289","1202","1175","1081","1043","997","1002","945","937","912","808","790","712","669","648","637","687","615","564","548","549","495","495","494","492","491","491","491","490","489","489","459","451","463","542","556","596","632","662","611","600","642","638","583","609","581","599","672","698","728","756","861","894","930","1112","1150","1162","1339","1660","1724","1696","1863","2236","2404","2638","3017"]},{"columns":["Himachal Pradesh","**65242** (↑404)","**3577** (↑136)","**60595** (↑258)","**1070** (↑10)","3577","60595","1070","2615","2394","2202","1830","1646","1439","1281","1220","1182","1088","971","874","810","830","811","767","755","697","628","584","575","556","516","469","436","408","361","331","339","343","383","390","378","365","409","439","462","497","464","458","455","488","493","505","524","411","398","370","354","301","298","252","234","227","218","229","244","261","292","318","434","437","495","540","589","589","614","617","621","599","662","706","745","760","757","820","935","1043","1124","1199","1256","1385","1455","1654","1903","2124","2361","2478","2634","2830","2973","3221","3338","3441","3577"]},{"columns":["Goa","**59068** (↑265)","**2077** (↑97)","**56156** (↑167)","**835** (↑1)","2077","56156","835","939","930","921","901","851","860","870","899","877","867","832","799","797","814","848","866","877","878","865","862","865","865","854","873","824","767","774","737","768","742","759","750","724","768","761","782","760","769","761","733","692","698","684","595","584","546","525","504","509","510","498","493","488","464","479","495","531","587","598","606","583","582","610","639","675","700","688","632","663","675","704","745","767","749","775","792","805","861","899","997","1013","1017","1089","1156","1278","1279","1379","1404","1429","1419","1556","1716","1914","1980","2077"]},{"columns":["Puducherry","**42359** (↑227)","**1592** (↑118)","**40083** (↑109)","**684**","1592","40083","684","384","366","346","358","357","373","372","359","343","328","316","304","293","278","298","294","286","284","286","297","296","299","294","302","288","280","295","282","291","295","306","285","285","286","279","293","314","317","312","309","307","293","296","284","284","258","236","213","202","199","177","188","192","174","179","189","196","194","197","185","177","174","168","166","176","173","176","171","178","179","176","186","191","190","186","180","214","6","67","127","190","236","322","445","540","636","763","900","991","1011","1074","1290","1420","1474","1592"]},{"columns":["Tripura","**33540** (↑3)","**63**","**33085** (↑10)","**392**","63","33085","392","104","96","88","83","73","64","64","59","60","57","50","49","46","45","45","41","38","39","39","38","37","40","34","35","32","28","24","21","21","21","21","19","17","15","12","12","11","11","8","7","7","5","3","2","2","2","2","4","5","14","40","41","41","45","47","25","32","32","41","39","42","40","33","32","31","30","30","30","24","18","17","10","12","13","20","11","12","21","25","30","30","34","43","43","44","51","49","47","49","56","60","59","56","70","63"]},{"columns":["Manipur","**29423** (↑8)","**61** (↑1)","**28988** (↑7)","**374**","61","28988","374","1155","1108","1104","1108","1109","442","479","490","480","515","490","477","481","469","446","436","380","343","296","235","244","220","197","196","201","186","171","161","153","142","136","144","139","138","111","113","113","109","99","85","77","49","53","56","66","75","76","83","91","83","85","84","80","49","36","41","40","37","44","33","30","33","32","32","33","31","28","29","30","35","36","30","27","26","24","24","28","28","24","28","29","33","44","53","57","60","58","63","67","67","70","64","57","60","61"]},{"columns":["Chandigarh","**28194** (↑341)","**3150**","**24661** (↑352)","**383** (↑1)","3150","24661","383","386","372","320","281","267","240","256","240","238","228","241","259","270","292","273","266","238","229","203","185","171","146","137","127","136","142","139","146","158","159","151","165","176","182","186","187","187","184","169","169","168","158","140","142","123","127","129","133","142","150","156","169","186","205","227","250","279","322","357","381","430","472","503","545","587","675","710","725","778","816","859","936","1032","1088","1166","1199","1330","1466","1597","1717","1872","1979","2066","2178","2286","2392","2532","2633","2746","2831","2918","2951","3098","3162","3150"]},{"columns":["Arunachal Pradesh","**16849**","**8**","**16785**","**56**","8","16785","56","99","97","95","93","87","79","88","79","77","64","66","63","61","58","68","64","62","58","57","52","46","38","37","37","18","15","14","15","15","13","14","13","10","11","9","8","8","7","7","5","4","4","5","5","4","3","3","3","3","5","5","5","5","5","4","4","3","3","3","","1","2","2","2","3","3","3","3","3","4","4","4","3","3","1","2","2","3","3","3","3","2","2","1","1","2","4","4","4","4","4","4","5","8","8"]},{"columns":["Meghalaya","**14122** (↑16)","**102** (↑14)","**13870** (↑2)","**150**","102","13870","150","149","164","136","135","139","149","154","138","155","163","155","151","152","160","161","161","148","148","148","133","133","129","128","122","111","104","98","89","90","83","74","68","62","56","52","63","81","102","137","134","137","164","166","164","166","149","128","100","78","55","38","26","22","22","20","18","20","19","17","17","17","15","14","13","14","12","13","12","14","19","20","20","26","29","29","31","30","32","31","28","30","29","25","22","23","26","26","26","26","45","49","50","64","88","102"]},{"columns":["Nagaland","**12363** (↑1)","**133** (↑1)","**12138**","**92**","133","12138","92","202","191","186","178","173","144","137","131","129","113","116","108","106","103","124","104","117","116","115","112","106","107","104","104","103","96","95","57","52","53","52","56","54","55","66","63","68","85","95","84","88","87","89","77","76","73","58","41","36","29","20","18","13","12","12","8","13","9","10","7","7","7","12","15","15","15","20","19","18","10","10","10","14","14","14","14","7","7","2","2","2","2","2","2","4","4","4","4","7","7","112","115","131","132","133"]},{"columns":["Ladakh","**10255** (↑29)","**323** (↑17)","**9802** (↑12)","**130**","323","9802","130","195","245","260","256","240","235","219","215","203","203","197","183","180","136","114","104","93","91","81","79","76","73","68","62","65","54","51","48","63","68","70","67","68","66","70","72","72","72","72","71","59","60","52","50","49","45","48","48","48","48","41","40","39","37","45","53","56","54","54","53","46","44","42","43","42","44","44","44","43","39","41","30","31","31","34","43","44","51","53","73","74","83","90","101","105","111","117","108","135","222","256","267","278","306","323"]},{"columns":["Sikkim","**6257** (↑6)","**51** (↑3)","**6071** (↑3)","**135**","51","6071","135","529","534","530","506","485","493","464","465","393","369","351","322","313","311","162","163","158","161","152","156","160","148","140","134","127","115","104","102","104","97","94","86","82","85","86","82","77","75","70","67","63","60","62","61","59","56","54","56","54","58","54","53","52","49","47","47","43","45","44","46","45","37","29","32","35","44","50","50","50","49","50","54","47","46","41","44","46","48","49","53","54","49","42","43","40","41","50","44","43","48","47","46","46","48","51"]},{"columns":["Andaman and Nicobar Islands","**5109** (↑11)","**57** (↑8)","**4990** (↑3)","**62**","57","4990","62","57","54","48","40","38","31","28","32","31","24","23","17","18","16","23","22","25","25","29","30","29","25","23","24","23","15","15","10","8","5","4","4","","","","","3","6","7","11","13","13","13","11","9","9","9","8","8","8","4","3","3","4","5","4","2","3","4","6","6","6","8","9","8","7","7","7","8","6","6","6","4","5","3","3","6","5","7","7","8","8","5","6","6","7","7","8","14","43","45","42","41","49","57"]},{"columns":["Mizoram","**4491** (↑1)","**41** (↑1)","**4439**","**11**","41","4439","11","110","111","104","88","79","86","88","79","82","98","92","96","94","101","96","80","85","79","79","67","69","64","58","58","53","49","47","42","41","39","40","33","31","33","30","25","27","23","24","24","21","22","21","20","20","17","18","18","20","23","24","22","22","21","24","23","27","26","25","20","20","20","19","18","14","9","8","10","9","9","9","9","10","11","12","15","17","13","14","15","14","17","18","18","24","26","26","26","29","28","31","37","40","40","41"]},{"columns":["Dadra and Nagar Haveli and Daman and Diu","**3744** (↑25)","**204** (↑5)","**3538** (↑20)","**2**","204","3538","2","11","11","11","9","8","7","5","5","5","4","2","4","4","4","6","9","9","11","11","9","11","10","10","10","6","5","5","6","7","8","6","6","5","4","4","4","2","1","1","","","","","","2","2","2","2","4","4","4","4","4","4","2","4","5","4","4","4","4","6","6","6","6","5","12","17","17","20","20","24","28","31","31","27","26","30","38","44","52","52","60","70","92","109","130","147","158","166","177","191","202","199","204"]},{"columns":["Lakshadweep","**741** (↑1)","**36**","**704** (↑3)","**1**","36","704","1","","","","","","","","","","","","","","","","","","","14","21","30","48","50","57","59","67","69","69","69","56","49","38","43","63","61","65","76","86","88","78","73","63","68","69","90","97","91","93","97","96","91","85","76","80","80","86","86","80","98","120","128","137","128","115","156","159","158","164","167","168","194","206","208","203","189","167","179","173","157","136","129","109","104","104","111","99","88","57","45","39","42","37","42","38","36"]}]}
import pandas as pd
df = pd.DataFrame(column_names[0]['rows'],data['rows'][0]['columns'])
df.head()

                                  columns
## India                            State
**12589067** (↑103558)             Cases*
**741830** (↑50233)               Active*
**11682136** (↑52847)   Cured/Discharged*
**165101** (↑478)                 Deaths*